[package]
name = "rakune"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.74"
futures = "0.3.29"
reqwest = { version = "0.11.22", features = ["blocking"] }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
use = "0.0.0"
